// Generated by gencpp from file tiggo_msgs/Intersection.msg
// DO NOT EDIT!


#ifndef TIGGO_MSGS_MESSAGE_INTERSECTION_H
#define TIGGO_MSGS_MESSAGE_INTERSECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tiggo_msgs
{
template <class ContainerAllocator>
struct Intersection_
{
  typedef Intersection_<ContainerAllocator> Type;

  Intersection_()
    : state(0)
    , stop(0)
    , steer(0.0)  {
    }
  Intersection_(const ContainerAllocator& _alloc)
    : state(0)
    , stop(0)
    , steer(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _state_type;
  _state_type state;

   typedef int8_t _stop_type;
  _stop_type stop;

   typedef double _steer_type;
  _steer_type steer;




  typedef boost::shared_ptr< ::tiggo_msgs::Intersection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiggo_msgs::Intersection_<ContainerAllocator> const> ConstPtr;

}; // struct Intersection_

typedef ::tiggo_msgs::Intersection_<std::allocator<void> > Intersection;

typedef boost::shared_ptr< ::tiggo_msgs::Intersection > IntersectionPtr;
typedef boost::shared_ptr< ::tiggo_msgs::Intersection const> IntersectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiggo_msgs::Intersection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiggo_msgs::Intersection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tiggo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tiggo_msgs': ['/home/hl/google/src/tiggo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::Intersection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::Intersection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::Intersection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::Intersection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::Intersection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::Intersection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiggo_msgs::Intersection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79115c01ac69e86c573d8bdbf1669193";
  }

  static const char* value(const ::tiggo_msgs::Intersection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79115c01ac69e86cULL;
  static const uint64_t static_value2 = 0x573d8bdbf1669193ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiggo_msgs::Intersection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiggo_msgs/Intersection";
  }

  static const char* value(const ::tiggo_msgs::Intersection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiggo_msgs::Intersection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 state\n\
int8 stop\n\
float64 steer\n\
";
  }

  static const char* value(const ::tiggo_msgs::Intersection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiggo_msgs::Intersection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.stop);
      stream.next(m.steer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Intersection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiggo_msgs::Intersection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiggo_msgs::Intersection_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "stop: ";
    Printer<int8_t>::stream(s, indent + "  ", v.stop);
    s << indent << "steer: ";
    Printer<double>::stream(s, indent + "  ", v.steer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIGGO_MSGS_MESSAGE_INTERSECTION_H
