// Generated by gencpp from file tiggo_msgs/LocalTarget.msg
// DO NOT EDIT!


#ifndef TIGGO_MSGS_MESSAGE_LOCALTARGET_H
#define TIGGO_MSGS_MESSAGE_LOCALTARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tiggo_msgs
{
template <class ContainerAllocator>
struct LocalTarget_
{
  typedef LocalTarget_<ContainerAllocator> Type;

  LocalTarget_()
    : property(0)
    , vaild(0)
    , x(0.0)
    , y(0.0)
    , angle(0.0)  {
    }
  LocalTarget_(const ContainerAllocator& _alloc)
    : property(0)
    , vaild(0)
    , x(0.0)
    , y(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _property_type;
  _property_type property;

   typedef int8_t _vaild_type;
  _vaild_type vaild;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::tiggo_msgs::LocalTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiggo_msgs::LocalTarget_<ContainerAllocator> const> ConstPtr;

}; // struct LocalTarget_

typedef ::tiggo_msgs::LocalTarget_<std::allocator<void> > LocalTarget;

typedef boost::shared_ptr< ::tiggo_msgs::LocalTarget > LocalTargetPtr;
typedef boost::shared_ptr< ::tiggo_msgs::LocalTarget const> LocalTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiggo_msgs::LocalTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiggo_msgs::LocalTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tiggo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tiggo_msgs': ['/home/hl/google/src/tiggo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::LocalTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::LocalTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::LocalTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::LocalTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::LocalTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::LocalTarget_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiggo_msgs::LocalTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d47eff1db0e203a12ea8fa15fa0df5a";
  }

  static const char* value(const ::tiggo_msgs::LocalTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d47eff1db0e203aULL;
  static const uint64_t static_value2 = 0x12ea8fa15fa0df5aULL;
};

template<class ContainerAllocator>
struct DataType< ::tiggo_msgs::LocalTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiggo_msgs/LocalTarget";
  }

  static const char* value(const ::tiggo_msgs::LocalTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiggo_msgs::LocalTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 property\n\
int8 vaild\n\
float64 x\n\
float64 y\n\
float64 angle\n\
";
  }

  static const char* value(const ::tiggo_msgs::LocalTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiggo_msgs::LocalTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.property);
      stream.next(m.vaild);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiggo_msgs::LocalTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiggo_msgs::LocalTarget_<ContainerAllocator>& v)
  {
    s << indent << "property: ";
    Printer<int8_t>::stream(s, indent + "  ", v.property);
    s << indent << "vaild: ";
    Printer<int8_t>::stream(s, indent + "  ", v.vaild);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIGGO_MSGS_MESSAGE_LOCALTARGET_H
