// Generated by gencpp from file tiggo_msgs/Path.msg
// DO NOT EDIT!


#ifndef TIGGO_MSGS_MESSAGE_PATH_H
#define TIGGO_MSGS_MESSAGE_PATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tiggo_msgs/Point2f.h>

namespace tiggo_msgs
{
template <class ContainerAllocator>
struct Path_
{
  typedef Path_<ContainerAllocator> Type;

  Path_()
    : header()
    , state(0)
    , length(0.0)
    , angle(0.0)
    , totalCost(0.0)
    , point()  {
    }
  Path_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , length(0.0)
    , angle(0.0)
    , totalCost(0.0)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _state_type;
  _state_type state;

   typedef float _length_type;
  _length_type length;

   typedef float _angle_type;
  _angle_type angle;

   typedef float _totalCost_type;
  _totalCost_type totalCost;

   typedef std::vector< ::tiggo_msgs::Point2f_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tiggo_msgs::Point2f_<ContainerAllocator> >::other >  _point_type;
  _point_type point;




  typedef boost::shared_ptr< ::tiggo_msgs::Path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiggo_msgs::Path_<ContainerAllocator> const> ConstPtr;

}; // struct Path_

typedef ::tiggo_msgs::Path_<std::allocator<void> > Path;

typedef boost::shared_ptr< ::tiggo_msgs::Path > PathPtr;
typedef boost::shared_ptr< ::tiggo_msgs::Path const> PathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiggo_msgs::Path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiggo_msgs::Path_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tiggo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tiggo_msgs': ['/home/hl/google/src/tiggo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::Path_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::Path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::Path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::Path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::Path_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiggo_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe1cb02a75fae0f1f114af824b8e7827";
  }

  static const char* value(const ::tiggo_msgs::Path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe1cb02a75fae0f1ULL;
  static const uint64_t static_value2 = 0xf114af824b8e7827ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiggo_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiggo_msgs/Path";
  }

  static const char* value(const ::tiggo_msgs::Path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiggo_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int8 state\n\
float32 length\n\
float32 angle\n\
float32 totalCost\n\
Point2f[] point\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: tiggo_msgs/Point2f\n\
float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::tiggo_msgs::Path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiggo_msgs::Path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.length);
      stream.next(m.angle);
      stream.next(m.totalCost);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiggo_msgs::Path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiggo_msgs::Path_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "totalCost: ";
    Printer<float>::stream(s, indent + "  ", v.totalCost);
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tiggo_msgs::Point2f_<ContainerAllocator> >::stream(s, indent + "    ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIGGO_MSGS_MESSAGE_PATH_H
