// Generated by gencpp from file tiggo_msgs/PixelLane.msg
// DO NOT EDIT!


#ifndef TIGGO_MSGS_MESSAGE_PIXELLANE_H
#define TIGGO_MSGS_MESSAGE_PIXELLANE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tiggo_msgs/Line2f.h>
#include <tiggo_msgs/Line2f.h>
#include <tiggo_msgs/Line2f.h>
#include <tiggo_msgs/Line2f.h>

namespace tiggo_msgs
{
template <class ContainerAllocator>
struct PixelLane_
{
  typedef PixelLane_<ContainerAllocator> Type;

  PixelLane_()
    : header()
    , num(0)
    , l0()
    , l1()
    , r0()
    , r1()  {
    }
  PixelLane_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num(0)
    , l0(_alloc)
    , l1(_alloc)
    , r0(_alloc)
    , r1(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _num_type;
  _num_type num;

   typedef  ::tiggo_msgs::Line2f_<ContainerAllocator>  _l0_type;
  _l0_type l0;

   typedef  ::tiggo_msgs::Line2f_<ContainerAllocator>  _l1_type;
  _l1_type l1;

   typedef  ::tiggo_msgs::Line2f_<ContainerAllocator>  _r0_type;
  _r0_type r0;

   typedef  ::tiggo_msgs::Line2f_<ContainerAllocator>  _r1_type;
  _r1_type r1;




  typedef boost::shared_ptr< ::tiggo_msgs::PixelLane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiggo_msgs::PixelLane_<ContainerAllocator> const> ConstPtr;

}; // struct PixelLane_

typedef ::tiggo_msgs::PixelLane_<std::allocator<void> > PixelLane;

typedef boost::shared_ptr< ::tiggo_msgs::PixelLane > PixelLanePtr;
typedef boost::shared_ptr< ::tiggo_msgs::PixelLane const> PixelLaneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiggo_msgs::PixelLane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiggo_msgs::PixelLane_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tiggo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tiggo_msgs': ['/home/hl/google/src/tiggo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::PixelLane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::PixelLane_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::PixelLane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::PixelLane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::PixelLane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::PixelLane_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiggo_msgs::PixelLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4116c3be631708dc81e93ce704fa097f";
  }

  static const char* value(const ::tiggo_msgs::PixelLane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4116c3be631708dcULL;
  static const uint64_t static_value2 = 0x81e93ce704fa097fULL;
};

template<class ContainerAllocator>
struct DataType< ::tiggo_msgs::PixelLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiggo_msgs/PixelLane";
  }

  static const char* value(const ::tiggo_msgs::PixelLane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiggo_msgs::PixelLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int8 num\n\
Line2f l0\n\
Line2f l1\n\
Line2f r0\n\
Line2f r1\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: tiggo_msgs/Line2f\n\
int8 vaild\n\
Point2f pt0\n\
Point2f pt1\n\
float64 slope\n\
float64 angle\n\
float64 len\n\
\n\
================================================================================\n\
MSG: tiggo_msgs/Point2f\n\
float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::tiggo_msgs::PixelLane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiggo_msgs::PixelLane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num);
      stream.next(m.l0);
      stream.next(m.l1);
      stream.next(m.r0);
      stream.next(m.r1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PixelLane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiggo_msgs::PixelLane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiggo_msgs::PixelLane_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num);
    s << indent << "l0: ";
    s << std::endl;
    Printer< ::tiggo_msgs::Line2f_<ContainerAllocator> >::stream(s, indent + "  ", v.l0);
    s << indent << "l1: ";
    s << std::endl;
    Printer< ::tiggo_msgs::Line2f_<ContainerAllocator> >::stream(s, indent + "  ", v.l1);
    s << indent << "r0: ";
    s << std::endl;
    Printer< ::tiggo_msgs::Line2f_<ContainerAllocator> >::stream(s, indent + "  ", v.r0);
    s << indent << "r1: ";
    s << std::endl;
    Printer< ::tiggo_msgs::Line2f_<ContainerAllocator> >::stream(s, indent + "  ", v.r1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIGGO_MSGS_MESSAGE_PIXELLANE_H
