// Generated by gencpp from file tiggo_msgs/StereoObjMultiArray.msg
// DO NOT EDIT!


#ifndef TIGGO_MSGS_MESSAGE_STEREOOBJMULTIARRAY_H
#define TIGGO_MSGS_MESSAGE_STEREOOBJMULTIARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tiggo_msgs/Point3f.h>

namespace tiggo_msgs
{
template <class ContainerAllocator>
struct StereoObjMultiArray_
{
  typedef StereoObjMultiArray_<ContainerAllocator> Type;

  StereoObjMultiArray_()
    : data()  {
    }
  StereoObjMultiArray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::tiggo_msgs::Point3f_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tiggo_msgs::Point3f_<ContainerAllocator> >::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> const> ConstPtr;

}; // struct StereoObjMultiArray_

typedef ::tiggo_msgs::StereoObjMultiArray_<std::allocator<void> > StereoObjMultiArray;

typedef boost::shared_ptr< ::tiggo_msgs::StereoObjMultiArray > StereoObjMultiArrayPtr;
typedef boost::shared_ptr< ::tiggo_msgs::StereoObjMultiArray const> StereoObjMultiArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tiggo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tiggo_msgs': ['/home/hl/google/src/tiggo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ce5b811f191fd19ad54fc0584fc5415";
  }

  static const char* value(const ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ce5b811f191fd19ULL;
  static const uint64_t static_value2 = 0xad54fc0584fc5415ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiggo_msgs/StereoObjMultiArray";
  }

  static const char* value(const ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point3f[] data\n\
\n\
================================================================================\n\
MSG: tiggo_msgs/Point3f\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StereoObjMultiArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiggo_msgs::StereoObjMultiArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tiggo_msgs::Point3f_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIGGO_MSGS_MESSAGE_STEREOOBJMULTIARRAY_H
