// Generated by gencpp from file tiggo_msgs/TrafficLightSend.msg
// DO NOT EDIT!


#ifndef TIGGO_MSGS_MESSAGE_TRAFFICLIGHTSEND_H
#define TIGGO_MSGS_MESSAGE_TRAFFICLIGHTSEND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tiggo_msgs
{
template <class ContainerAllocator>
struct TrafficLightSend_
{
  typedef TrafficLightSend_<ContainerAllocator> Type;

  TrafficLightSend_()
    : header()
    , left_stop(false)
    , front_stop(false)
    , right_stop(false)  {
    }
  TrafficLightSend_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_stop(false)
    , front_stop(false)
    , right_stop(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _left_stop_type;
  _left_stop_type left_stop;

   typedef uint8_t _front_stop_type;
  _front_stop_type front_stop;

   typedef uint8_t _right_stop_type;
  _right_stop_type right_stop;




  typedef boost::shared_ptr< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLightSend_

typedef ::tiggo_msgs::TrafficLightSend_<std::allocator<void> > TrafficLightSend;

typedef boost::shared_ptr< ::tiggo_msgs::TrafficLightSend > TrafficLightSendPtr;
typedef boost::shared_ptr< ::tiggo_msgs::TrafficLightSend const> TrafficLightSendConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tiggo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tiggo_msgs': ['/home/hl/google/src/tiggo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8617fed90f265fe8694e76c5b1f30b9";
  }

  static const char* value(const ::tiggo_msgs::TrafficLightSend_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8617fed90f265feULL;
  static const uint64_t static_value2 = 0x8694e76c5b1f30b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiggo_msgs/TrafficLightSend";
  }

  static const char* value(const ::tiggo_msgs::TrafficLightSend_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool left_stop\n\
bool front_stop\n\
bool right_stop\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tiggo_msgs::TrafficLightSend_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_stop);
      stream.next(m.front_stop);
      stream.next(m.right_stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficLightSend_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiggo_msgs::TrafficLightSend_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiggo_msgs::TrafficLightSend_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_stop);
    s << indent << "front_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.front_stop);
    s << indent << "right_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIGGO_MSGS_MESSAGE_TRAFFICLIGHTSEND_H
