// Generated by gencpp from file tiggo_msgs/Tunnel.msg
// DO NOT EDIT!


#ifndef TIGGO_MSGS_MESSAGE_TUNNEL_H
#define TIGGO_MSGS_MESSAGE_TUNNEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tiggo_msgs
{
template <class ContainerAllocator>
struct Tunnel_
{
  typedef Tunnel_<ContainerAllocator> Type;

  Tunnel_()
    : is_in_tunnel(0)  {
    }
  Tunnel_(const ContainerAllocator& _alloc)
    : is_in_tunnel(0)  {
  (void)_alloc;
    }



   typedef int8_t _is_in_tunnel_type;
  _is_in_tunnel_type is_in_tunnel;




  typedef boost::shared_ptr< ::tiggo_msgs::Tunnel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiggo_msgs::Tunnel_<ContainerAllocator> const> ConstPtr;

}; // struct Tunnel_

typedef ::tiggo_msgs::Tunnel_<std::allocator<void> > Tunnel;

typedef boost::shared_ptr< ::tiggo_msgs::Tunnel > TunnelPtr;
typedef boost::shared_ptr< ::tiggo_msgs::Tunnel const> TunnelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiggo_msgs::Tunnel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiggo_msgs::Tunnel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tiggo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tiggo_msgs': ['/home/hl/google/src/tiggo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::Tunnel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::Tunnel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::Tunnel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::Tunnel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::Tunnel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::Tunnel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiggo_msgs::Tunnel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24dfabdca5c0f6448bcccc06249ea950";
  }

  static const char* value(const ::tiggo_msgs::Tunnel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24dfabdca5c0f644ULL;
  static const uint64_t static_value2 = 0x8bcccc06249ea950ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiggo_msgs::Tunnel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiggo_msgs/Tunnel";
  }

  static const char* value(const ::tiggo_msgs::Tunnel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiggo_msgs::Tunnel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 is_in_tunnel\n\
";
  }

  static const char* value(const ::tiggo_msgs::Tunnel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiggo_msgs::Tunnel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_in_tunnel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Tunnel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiggo_msgs::Tunnel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiggo_msgs::Tunnel_<ContainerAllocator>& v)
  {
    s << indent << "is_in_tunnel: ";
    Printer<int8_t>::stream(s, indent + "  ", v.is_in_tunnel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIGGO_MSGS_MESSAGE_TUNNEL_H
