// Generated by gencpp from file can_msgs/ControllerInstruction.msg
// DO NOT EDIT!


#ifndef CAN_MSGS_MESSAGE_CONTROLLERINSTRUCTION_H
#define CAN_MSGS_MESSAGE_CONTROLLERINSTRUCTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace can_msgs
{
template <class ContainerAllocator>
struct ControllerInstruction_
{
  typedef ControllerInstruction_<ContainerAllocator> Type;

  ControllerInstruction_()
    : header()
    , SpeedCmd(0.0)
    , SteerCmd(0.0)  {
    }
  ControllerInstruction_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , SpeedCmd(0.0)
    , SteerCmd(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _SpeedCmd_type;
  _SpeedCmd_type SpeedCmd;

   typedef float _SteerCmd_type;
  _SteerCmd_type SteerCmd;




  typedef boost::shared_ptr< ::can_msgs::ControllerInstruction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_msgs::ControllerInstruction_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerInstruction_

typedef ::can_msgs::ControllerInstruction_<std::allocator<void> > ControllerInstruction;

typedef boost::shared_ptr< ::can_msgs::ControllerInstruction > ControllerInstructionPtr;
typedef boost::shared_ptr< ::can_msgs::ControllerInstruction const> ControllerInstructionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_msgs::ControllerInstruction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_msgs::ControllerInstruction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'can_msgs': ['/home/hl/google/src/can_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::ControllerInstruction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::ControllerInstruction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::ControllerInstruction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::ControllerInstruction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::ControllerInstruction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::ControllerInstruction_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_msgs::ControllerInstruction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2882926008a24c6b1135d4df7ed2d36c";
  }

  static const char* value(const ::can_msgs::ControllerInstruction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2882926008a24c6bULL;
  static const uint64_t static_value2 = 0x1135d4df7ed2d36cULL;
};

template<class ContainerAllocator>
struct DataType< ::can_msgs::ControllerInstruction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_msgs/ControllerInstruction";
  }

  static const char* value(const ::can_msgs::ControllerInstruction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_msgs::ControllerInstruction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 SpeedCmd\n\
float32 SteerCmd\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::can_msgs::ControllerInstruction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_msgs::ControllerInstruction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.SpeedCmd);
      stream.next(m.SteerCmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerInstruction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_msgs::ControllerInstruction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_msgs::ControllerInstruction_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "SpeedCmd: ";
    Printer<float>::stream(s, indent + "  ", v.SpeedCmd);
    s << indent << "SteerCmd: ";
    Printer<float>::stream(s, indent + "  ", v.SteerCmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_MSGS_MESSAGE_CONTROLLERINSTRUCTION_H
