// Generated by gencpp from file can_msgs/Float64Pair.msg
// DO NOT EDIT!


#ifndef CAN_MSGS_MESSAGE_FLOAT64PAIR_H
#define CAN_MSGS_MESSAGE_FLOAT64PAIR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace can_msgs
{
template <class ContainerAllocator>
struct Float64Pair_
{
  typedef Float64Pair_<ContainerAllocator> Type;

  Float64Pair_()
    : header()
    , first(0.0)
    , second(0.0)  {
    }
  Float64Pair_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , first(0.0)
    , second(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _first_type;
  _first_type first;

   typedef double _second_type;
  _second_type second;




  typedef boost::shared_ptr< ::can_msgs::Float64Pair_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_msgs::Float64Pair_<ContainerAllocator> const> ConstPtr;

}; // struct Float64Pair_

typedef ::can_msgs::Float64Pair_<std::allocator<void> > Float64Pair;

typedef boost::shared_ptr< ::can_msgs::Float64Pair > Float64PairPtr;
typedef boost::shared_ptr< ::can_msgs::Float64Pair const> Float64PairConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_msgs::Float64Pair_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_msgs::Float64Pair_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'can_msgs': ['/home/hl/google/src/can_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::Float64Pair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::Float64Pair_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::Float64Pair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::Float64Pair_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::Float64Pair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::Float64Pair_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_msgs::Float64Pair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7106b3cff60682b7a71683a68d8f1b8d";
  }

  static const char* value(const ::can_msgs::Float64Pair_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7106b3cff60682b7ULL;
  static const uint64_t static_value2 = 0xa71683a68d8f1b8dULL;
};

template<class ContainerAllocator>
struct DataType< ::can_msgs::Float64Pair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_msgs/Float64Pair";
  }

  static const char* value(const ::can_msgs::Float64Pair_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_msgs::Float64Pair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 first\n\
float64 second\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::can_msgs::Float64Pair_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_msgs::Float64Pair_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.first);
      stream.next(m.second);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Float64Pair_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_msgs::Float64Pair_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_msgs::Float64Pair_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "first: ";
    Printer<double>::stream(s, indent + "  ", v.first);
    s << indent << "second: ";
    Printer<double>::stream(s, indent + "  ", v.second);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_MSGS_MESSAGE_FLOAT64PAIR_H
