// Generated by gencpp from file can_msgs/Float64Vector.msg
// DO NOT EDIT!


#ifndef CAN_MSGS_MESSAGE_FLOAT64VECTOR_H
#define CAN_MSGS_MESSAGE_FLOAT64VECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace can_msgs
{
template <class ContainerAllocator>
struct Float64Vector_
{
  typedef Float64Vector_<ContainerAllocator> Type;

  Float64Vector_()
    : header()
    , float_vector()  {
    }
  Float64Vector_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , float_vector(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _float_vector_type;
  _float_vector_type float_vector;




  typedef boost::shared_ptr< ::can_msgs::Float64Vector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_msgs::Float64Vector_<ContainerAllocator> const> ConstPtr;

}; // struct Float64Vector_

typedef ::can_msgs::Float64Vector_<std::allocator<void> > Float64Vector;

typedef boost::shared_ptr< ::can_msgs::Float64Vector > Float64VectorPtr;
typedef boost::shared_ptr< ::can_msgs::Float64Vector const> Float64VectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_msgs::Float64Vector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_msgs::Float64Vector_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'can_msgs': ['/home/hl/google/src/can_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::Float64Vector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::Float64Vector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::Float64Vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::Float64Vector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::Float64Vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::Float64Vector_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_msgs::Float64Vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f62a7b3ed764d1e819a56b33dbf9e59c";
  }

  static const char* value(const ::can_msgs::Float64Vector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf62a7b3ed764d1e8ULL;
  static const uint64_t static_value2 = 0x19a56b33dbf9e59cULL;
};

template<class ContainerAllocator>
struct DataType< ::can_msgs::Float64Vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_msgs/Float64Vector";
  }

  static const char* value(const ::can_msgs::Float64Vector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_msgs::Float64Vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64[] float_vector\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::can_msgs::Float64Vector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_msgs::Float64Vector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.float_vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Float64Vector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_msgs::Float64Vector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_msgs::Float64Vector_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "float_vector[]" << std::endl;
    for (size_t i = 0; i < v.float_vector.size(); ++i)
    {
      s << indent << "  float_vector[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.float_vector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_MSGS_MESSAGE_FLOAT64VECTOR_H
