// Generated by gencpp from file can_msgs/MagGPSInfo4Fusion.msg
// DO NOT EDIT!


#ifndef CAN_MSGS_MESSAGE_MAGGPSINFO4FUSION_H
#define CAN_MSGS_MESSAGE_MAGGPSINFO4FUSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace can_msgs
{
template <class ContainerAllocator>
struct MagGPSInfo4Fusion_
{
  typedef MagGPSInfo4Fusion_<ContainerAllocator> Type;

  MagGPSInfo4Fusion_()
    : header()
    , TimeOfIssue()
    , MagOffsetFromMiddle(0.0)
    , Cnt(0)
    , task_id(0)
    , link_id(0)
    , ForceUpdate(0)
    , Polarity(0)
    , PolarityCode(0)
    , AdjMagnetArray()  {
    }
  MagGPSInfo4Fusion_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , TimeOfIssue()
    , MagOffsetFromMiddle(0.0)
    , Cnt(0)
    , task_id(0)
    , link_id(0)
    , ForceUpdate(0)
    , Polarity(0)
    , PolarityCode(0)
    , AdjMagnetArray(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _TimeOfIssue_type;
  _TimeOfIssue_type TimeOfIssue;

   typedef float _MagOffsetFromMiddle_type;
  _MagOffsetFromMiddle_type MagOffsetFromMiddle;

   typedef int32_t _Cnt_type;
  _Cnt_type Cnt;

   typedef int32_t _task_id_type;
  _task_id_type task_id;

   typedef int32_t _link_id_type;
  _link_id_type link_id;

   typedef int32_t _ForceUpdate_type;
  _ForceUpdate_type ForceUpdate;

   typedef int32_t _Polarity_type;
  _Polarity_type Polarity;

   typedef int32_t _PolarityCode_type;
  _PolarityCode_type PolarityCode;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _AdjMagnetArray_type;
  _AdjMagnetArray_type AdjMagnetArray;




  typedef boost::shared_ptr< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> const> ConstPtr;

}; // struct MagGPSInfo4Fusion_

typedef ::can_msgs::MagGPSInfo4Fusion_<std::allocator<void> > MagGPSInfo4Fusion;

typedef boost::shared_ptr< ::can_msgs::MagGPSInfo4Fusion > MagGPSInfo4FusionPtr;
typedef boost::shared_ptr< ::can_msgs::MagGPSInfo4Fusion const> MagGPSInfo4FusionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'can_msgs': ['/home/hl/google/src/can_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49e8bcc1ce79d983333e55c4b60b9ab1";
  }

  static const char* value(const ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49e8bcc1ce79d983ULL;
  static const uint64_t static_value2 = 0x333e55c4b60b9ab1ULL;
};

template<class ContainerAllocator>
struct DataType< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_msgs/MagGPSInfo4Fusion";
  }

  static const char* value(const ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
time TimeOfIssue\n\
\n\
float32 MagOffsetFromMiddle\n\
int32   Cnt\n\
int32   task_id\n\
int32   link_id\n\
int32   ForceUpdate\n\
int32   Polarity\n\
int32   PolarityCode\n\
\n\
float32[] AdjMagnetArray\n\
\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.TimeOfIssue);
      stream.next(m.MagOffsetFromMiddle);
      stream.next(m.Cnt);
      stream.next(m.task_id);
      stream.next(m.link_id);
      stream.next(m.ForceUpdate);
      stream.next(m.Polarity);
      stream.next(m.PolarityCode);
      stream.next(m.AdjMagnetArray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagGPSInfo4Fusion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_msgs::MagGPSInfo4Fusion_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "TimeOfIssue: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.TimeOfIssue);
    s << indent << "MagOffsetFromMiddle: ";
    Printer<float>::stream(s, indent + "  ", v.MagOffsetFromMiddle);
    s << indent << "Cnt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Cnt);
    s << indent << "task_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_id);
    s << indent << "link_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.link_id);
    s << indent << "ForceUpdate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ForceUpdate);
    s << indent << "Polarity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Polarity);
    s << indent << "PolarityCode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.PolarityCode);
    s << indent << "AdjMagnetArray[]" << std::endl;
    for (size_t i = 0; i < v.AdjMagnetArray.size(); ++i)
    {
      s << indent << "  AdjMagnetArray[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.AdjMagnetArray[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_MSGS_MESSAGE_MAGGPSINFO4FUSION_H
