// Generated by gencpp from file can_msgs/MagUpdateFeedback.msg
// DO NOT EDIT!


#ifndef CAN_MSGS_MESSAGE_MAGUPDATEFEEDBACK_H
#define CAN_MSGS_MESSAGE_MAGUPDATEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace can_msgs
{
template <class ContainerAllocator>
struct MagUpdateFeedback_
{
  typedef MagUpdateFeedback_<ContainerAllocator> Type;

  MagUpdateFeedback_()
    : header()
    , TimeOfIssue()
    , UpdatedCnt(0)
    , XuEKF_InitOK(0)
    , UpdatedMag_Index(0)
    , UpdatedMag_X(0.0)
    , UpdatedMag_Y(0.0)  {
    }
  MagUpdateFeedback_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , TimeOfIssue()
    , UpdatedCnt(0)
    , XuEKF_InitOK(0)
    , UpdatedMag_Index(0)
    , UpdatedMag_X(0.0)
    , UpdatedMag_Y(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _TimeOfIssue_type;
  _TimeOfIssue_type TimeOfIssue;

   typedef int32_t _UpdatedCnt_type;
  _UpdatedCnt_type UpdatedCnt;

   typedef int32_t _XuEKF_InitOK_type;
  _XuEKF_InitOK_type XuEKF_InitOK;

   typedef int32_t _UpdatedMag_Index_type;
  _UpdatedMag_Index_type UpdatedMag_Index;

   typedef float _UpdatedMag_X_type;
  _UpdatedMag_X_type UpdatedMag_X;

   typedef float _UpdatedMag_Y_type;
  _UpdatedMag_Y_type UpdatedMag_Y;




  typedef boost::shared_ptr< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MagUpdateFeedback_

typedef ::can_msgs::MagUpdateFeedback_<std::allocator<void> > MagUpdateFeedback;

typedef boost::shared_ptr< ::can_msgs::MagUpdateFeedback > MagUpdateFeedbackPtr;
typedef boost::shared_ptr< ::can_msgs::MagUpdateFeedback const> MagUpdateFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_msgs::MagUpdateFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'can_msgs': ['/home/hl/google/src/can_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3df0e682ba87d78bb14b950e9861807d";
  }

  static const char* value(const ::can_msgs::MagUpdateFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3df0e682ba87d78bULL;
  static const uint64_t static_value2 = 0xb14b950e9861807dULL;
};

template<class ContainerAllocator>
struct DataType< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_msgs/MagUpdateFeedback";
  }

  static const char* value(const ::can_msgs::MagUpdateFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
time TimeOfIssue\n\
\n\
int32 UpdatedCnt\n\
int32 XuEKF_InitOK\n\
int32   UpdatedMag_Index\n\
float32 UpdatedMag_X\n\
float32 UpdatedMag_Y\n\
\n\
\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::can_msgs::MagUpdateFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.TimeOfIssue);
      stream.next(m.UpdatedCnt);
      stream.next(m.XuEKF_InitOK);
      stream.next(m.UpdatedMag_Index);
      stream.next(m.UpdatedMag_X);
      stream.next(m.UpdatedMag_Y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagUpdateFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_msgs::MagUpdateFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_msgs::MagUpdateFeedback_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "TimeOfIssue: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.TimeOfIssue);
    s << indent << "UpdatedCnt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.UpdatedCnt);
    s << indent << "XuEKF_InitOK: ";
    Printer<int32_t>::stream(s, indent + "  ", v.XuEKF_InitOK);
    s << indent << "UpdatedMag_Index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.UpdatedMag_Index);
    s << indent << "UpdatedMag_X: ";
    Printer<float>::stream(s, indent + "  ", v.UpdatedMag_X);
    s << indent << "UpdatedMag_Y: ";
    Printer<float>::stream(s, indent + "  ", v.UpdatedMag_Y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_MSGS_MESSAGE_MAGUPDATEFEEDBACK_H
