// Generated by gencpp from file can_msgs/ObstacleStop.msg
// DO NOT EDIT!


#ifndef CAN_MSGS_MESSAGE_OBSTACLESTOP_H
#define CAN_MSGS_MESSAGE_OBSTACLESTOP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace can_msgs
{
template <class ContainerAllocator>
struct ObstacleStop_
{
  typedef ObstacleStop_<ContainerAllocator> Type;

  ObstacleStop_()
    : header()
    , StopCmd(0)
    , SlowdownFlag(0)
    , RefSpeed(0.0)  {
    }
  ObstacleStop_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , StopCmd(0)
    , SlowdownFlag(0)
    , RefSpeed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _StopCmd_type;
  _StopCmd_type StopCmd;

   typedef uint8_t _SlowdownFlag_type;
  _SlowdownFlag_type SlowdownFlag;

   typedef float _RefSpeed_type;
  _RefSpeed_type RefSpeed;




  typedef boost::shared_ptr< ::can_msgs::ObstacleStop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_msgs::ObstacleStop_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleStop_

typedef ::can_msgs::ObstacleStop_<std::allocator<void> > ObstacleStop;

typedef boost::shared_ptr< ::can_msgs::ObstacleStop > ObstacleStopPtr;
typedef boost::shared_ptr< ::can_msgs::ObstacleStop const> ObstacleStopConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_msgs::ObstacleStop_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_msgs::ObstacleStop_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'can_msgs': ['/home/hl/google/src/can_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::ObstacleStop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::ObstacleStop_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::ObstacleStop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::ObstacleStop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::ObstacleStop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::ObstacleStop_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_msgs::ObstacleStop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c36e95047ae42ed329b7b25f11fe78f6";
  }

  static const char* value(const ::can_msgs::ObstacleStop_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc36e95047ae42ed3ULL;
  static const uint64_t static_value2 = 0x29b7b25f11fe78f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::can_msgs::ObstacleStop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_msgs/ObstacleStop";
  }

  static const char* value(const ::can_msgs::ObstacleStop_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_msgs::ObstacleStop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 StopCmd\n\
uint8 SlowdownFlag\n\
float32 RefSpeed\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::can_msgs::ObstacleStop_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_msgs::ObstacleStop_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.StopCmd);
      stream.next(m.SlowdownFlag);
      stream.next(m.RefSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleStop_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_msgs::ObstacleStop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_msgs::ObstacleStop_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "StopCmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.StopCmd);
    s << indent << "SlowdownFlag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.SlowdownFlag);
    s << indent << "RefSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.RefSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_MSGS_MESSAGE_OBSTACLESTOP_H
