# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tiggo_msgs/PixelLane.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tiggo_msgs.msg
import std_msgs.msg

class PixelLane(genpy.Message):
  _md5sum = "4116c3be631708dc81e93ce704fa097f"
  _type = "tiggo_msgs/PixelLane"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
int8 num
Line2f l0
Line2f l1
Line2f r0
Line2f r1

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: tiggo_msgs/Line2f
int8 vaild
Point2f pt0
Point2f pt1
float64 slope
float64 angle
float64 len

================================================================================
MSG: tiggo_msgs/Point2f
float32 x
float32 y
"""
  __slots__ = ['header','num','l0','l1','r0','r1']
  _slot_types = ['std_msgs/Header','int8','tiggo_msgs/Line2f','tiggo_msgs/Line2f','tiggo_msgs/Line2f','tiggo_msgs/Line2f']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,num,l0,l1,r0,r1

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PixelLane, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.num is None:
        self.num = 0
      if self.l0 is None:
        self.l0 = tiggo_msgs.msg.Line2f()
      if self.l1 is None:
        self.l1 = tiggo_msgs.msg.Line2f()
      if self.r0 is None:
        self.r0 = tiggo_msgs.msg.Line2f()
      if self.r1 is None:
        self.r1 = tiggo_msgs.msg.Line2f()
    else:
      self.header = std_msgs.msg.Header()
      self.num = 0
      self.l0 = tiggo_msgs.msg.Line2f()
      self.l1 = tiggo_msgs.msg.Line2f()
      self.r0 = tiggo_msgs.msg.Line2f()
      self.r1 = tiggo_msgs.msg.Line2f()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2b4f3db4f3db4f3db4f3d.pack(_x.num, _x.l0.vaild, _x.l0.pt0.x, _x.l0.pt0.y, _x.l0.pt1.x, _x.l0.pt1.y, _x.l0.slope, _x.l0.angle, _x.l0.len, _x.l1.vaild, _x.l1.pt0.x, _x.l1.pt0.y, _x.l1.pt1.x, _x.l1.pt1.y, _x.l1.slope, _x.l1.angle, _x.l1.len, _x.r0.vaild, _x.r0.pt0.x, _x.r0.pt0.y, _x.r0.pt1.x, _x.r0.pt1.y, _x.r0.slope, _x.r0.angle, _x.r0.len, _x.r1.vaild, _x.r1.pt0.x, _x.r1.pt0.y, _x.r1.pt1.x, _x.r1.pt1.y, _x.r1.slope, _x.r1.angle, _x.r1.len))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.l0 is None:
        self.l0 = tiggo_msgs.msg.Line2f()
      if self.l1 is None:
        self.l1 = tiggo_msgs.msg.Line2f()
      if self.r0 is None:
        self.r0 = tiggo_msgs.msg.Line2f()
      if self.r1 is None:
        self.r1 = tiggo_msgs.msg.Line2f()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 165
      (_x.num, _x.l0.vaild, _x.l0.pt0.x, _x.l0.pt0.y, _x.l0.pt1.x, _x.l0.pt1.y, _x.l0.slope, _x.l0.angle, _x.l0.len, _x.l1.vaild, _x.l1.pt0.x, _x.l1.pt0.y, _x.l1.pt1.x, _x.l1.pt1.y, _x.l1.slope, _x.l1.angle, _x.l1.len, _x.r0.vaild, _x.r0.pt0.x, _x.r0.pt0.y, _x.r0.pt1.x, _x.r0.pt1.y, _x.r0.slope, _x.r0.angle, _x.r0.len, _x.r1.vaild, _x.r1.pt0.x, _x.r1.pt0.y, _x.r1.pt1.x, _x.r1.pt1.y, _x.r1.slope, _x.r1.angle, _x.r1.len,) = _struct_2b4f3db4f3db4f3db4f3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2b4f3db4f3db4f3db4f3d.pack(_x.num, _x.l0.vaild, _x.l0.pt0.x, _x.l0.pt0.y, _x.l0.pt1.x, _x.l0.pt1.y, _x.l0.slope, _x.l0.angle, _x.l0.len, _x.l1.vaild, _x.l1.pt0.x, _x.l1.pt0.y, _x.l1.pt1.x, _x.l1.pt1.y, _x.l1.slope, _x.l1.angle, _x.l1.len, _x.r0.vaild, _x.r0.pt0.x, _x.r0.pt0.y, _x.r0.pt1.x, _x.r0.pt1.y, _x.r0.slope, _x.r0.angle, _x.r0.len, _x.r1.vaild, _x.r1.pt0.x, _x.r1.pt0.y, _x.r1.pt1.x, _x.r1.pt1.y, _x.r1.slope, _x.r1.angle, _x.r1.len))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.l0 is None:
        self.l0 = tiggo_msgs.msg.Line2f()
      if self.l1 is None:
        self.l1 = tiggo_msgs.msg.Line2f()
      if self.r0 is None:
        self.r0 = tiggo_msgs.msg.Line2f()
      if self.r1 is None:
        self.r1 = tiggo_msgs.msg.Line2f()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 165
      (_x.num, _x.l0.vaild, _x.l0.pt0.x, _x.l0.pt0.y, _x.l0.pt1.x, _x.l0.pt1.y, _x.l0.slope, _x.l0.angle, _x.l0.len, _x.l1.vaild, _x.l1.pt0.x, _x.l1.pt0.y, _x.l1.pt1.x, _x.l1.pt1.y, _x.l1.slope, _x.l1.angle, _x.l1.len, _x.r0.vaild, _x.r0.pt0.x, _x.r0.pt0.y, _x.r0.pt1.x, _x.r0.pt1.y, _x.r0.slope, _x.r0.angle, _x.r0.len, _x.r1.vaild, _x.r1.pt0.x, _x.r1.pt0.y, _x.r1.pt1.x, _x.r1.pt1.y, _x.r1.slope, _x.r1.angle, _x.r1.len,) = _struct_2b4f3db4f3db4f3db4f3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_2b4f3db4f3db4f3db4f3d = struct.Struct("<2b4f3db4f3db4f3db4f3d")
