// Generated by gencpp from file gl8_msgs/CanFrame.msg
// DO NOT EDIT!


#ifndef GL8_MSGS_MESSAGE_CANFRAME_H
#define GL8_MSGS_MESSAGE_CANFRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gl8_msgs
{
template <class ContainerAllocator>
struct CanFrame_
{
  typedef CanFrame_<ContainerAllocator> Type;

  CanFrame_()
    : header()
    , id(0)
    , len(0)
    , data()  {
      data.assign(0);
  }
  CanFrame_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , len(0)
    , data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _id_type;
  _id_type id;

   typedef int16_t _len_type;
  _len_type len;

   typedef boost::array<int32_t, 8>  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::gl8_msgs::CanFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gl8_msgs::CanFrame_<ContainerAllocator> const> ConstPtr;

}; // struct CanFrame_

typedef ::gl8_msgs::CanFrame_<std::allocator<void> > CanFrame;

typedef boost::shared_ptr< ::gl8_msgs::CanFrame > CanFramePtr;
typedef boost::shared_ptr< ::gl8_msgs::CanFrame const> CanFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gl8_msgs::CanFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gl8_msgs::CanFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gl8_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'gl8_msgs': ['/home/hl/google/src/gl8_msgs /msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::CanFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::CanFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::CanFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::CanFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::CanFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::CanFrame_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gl8_msgs::CanFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bcbc73126097cc03114a212cd73f49fb";
  }

  static const char* value(const ::gl8_msgs::CanFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbcbc73126097cc03ULL;
  static const uint64_t static_value2 = 0x114a212cd73f49fbULL;
};

template<class ContainerAllocator>
struct DataType< ::gl8_msgs::CanFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gl8_msgs/CanFrame";
  }

  static const char* value(const ::gl8_msgs::CanFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gl8_msgs::CanFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16 id \n\
int16 len \n\
int32[8] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gl8_msgs::CanFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gl8_msgs::CanFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.len);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CanFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gl8_msgs::CanFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gl8_msgs::CanFrame_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "len: ";
    Printer<int16_t>::stream(s, indent + "  ", v.len);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GL8_MSGS_MESSAGE_CANFRAME_H
