// Generated by gencpp from file gl8_msgs/GlobalPath.msg
// DO NOT EDIT!


#ifndef GL8_MSGS_MESSAGE_GLOBALPATH_H
#define GL8_MSGS_MESSAGE_GLOBALPATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <gl8_msgs/PathPoint.h>

namespace gl8_msgs
{
template <class ContainerAllocator>
struct GlobalPath_
{
  typedef GlobalPath_<ContainerAllocator> Type;

  GlobalPath_()
    : header()
    , points()  {
    }
  GlobalPath_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::gl8_msgs::PathPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::gl8_msgs::PathPoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;




  typedef boost::shared_ptr< ::gl8_msgs::GlobalPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gl8_msgs::GlobalPath_<ContainerAllocator> const> ConstPtr;

}; // struct GlobalPath_

typedef ::gl8_msgs::GlobalPath_<std::allocator<void> > GlobalPath;

typedef boost::shared_ptr< ::gl8_msgs::GlobalPath > GlobalPathPtr;
typedef boost::shared_ptr< ::gl8_msgs::GlobalPath const> GlobalPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gl8_msgs::GlobalPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gl8_msgs::GlobalPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gl8_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'gl8_msgs': ['/home/hl/google/src/gl8_msgs /msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::GlobalPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::GlobalPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::GlobalPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::GlobalPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::GlobalPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::GlobalPath_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gl8_msgs::GlobalPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97c8444c48d651c3d01549eb1d8a5698";
  }

  static const char* value(const ::gl8_msgs::GlobalPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97c8444c48d651c3ULL;
  static const uint64_t static_value2 = 0xd01549eb1d8a5698ULL;
};

template<class ContainerAllocator>
struct DataType< ::gl8_msgs::GlobalPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gl8_msgs/GlobalPath";
  }

  static const char* value(const ::gl8_msgs::GlobalPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gl8_msgs::GlobalPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
PathPoint[] points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: gl8_msgs/PathPoint\n\
int16 id\n\
float64 x \n\
float64 y \n\
float64 theta\n\
float64 kappa\n\
";
  }

  static const char* value(const ::gl8_msgs::GlobalPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gl8_msgs::GlobalPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GlobalPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gl8_msgs::GlobalPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gl8_msgs::GlobalPath_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gl8_msgs::PathPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GL8_MSGS_MESSAGE_GLOBALPATH_H
