// Generated by gencpp from file gl8_msgs/GPGGA_MSG.msg
// DO NOT EDIT!


#ifndef GL8_MSGS_MESSAGE_GPGGA_MSG_H
#define GL8_MSGS_MESSAGE_GPGGA_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gl8_msgs
{
template <class ContainerAllocator>
struct GPGGA_MSG_
{
  typedef GPGGA_MSG_<ContainerAllocator> Type;

  GPGGA_MSG_()
    : header()
    , hdop(0.0)
    , num_satellites(0.0)
    , fix_type(0.0)  {
    }
  GPGGA_MSG_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , hdop(0.0)
    , num_satellites(0.0)
    , fix_type(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _hdop_type;
  _hdop_type hdop;

   typedef double _num_satellites_type;
  _num_satellites_type num_satellites;

   typedef double _fix_type_type;
  _fix_type_type fix_type;




  typedef boost::shared_ptr< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> const> ConstPtr;

}; // struct GPGGA_MSG_

typedef ::gl8_msgs::GPGGA_MSG_<std::allocator<void> > GPGGA_MSG;

typedef boost::shared_ptr< ::gl8_msgs::GPGGA_MSG > GPGGA_MSGPtr;
typedef boost::shared_ptr< ::gl8_msgs::GPGGA_MSG const> GPGGA_MSGConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gl8_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'gl8_msgs': ['/home/hl/google/src/gl8_msgs /msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "343d1faf34c0404519bb8dd620dccd5d";
  }

  static const char* value(const ::gl8_msgs::GPGGA_MSG_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x343d1faf34c04045ULL;
  static const uint64_t static_value2 = 0x19bb8dd620dccd5dULL;
};

template<class ContainerAllocator>
struct DataType< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gl8_msgs/GPGGA_MSG";
  }

  static const char* value(const ::gl8_msgs::GPGGA_MSG_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float64 hdop\n\
float64 num_satellites\n\
float64 fix_type\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gl8_msgs::GPGGA_MSG_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.hdop);
      stream.next(m.num_satellites);
      stream.next(m.fix_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPGGA_MSG_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gl8_msgs::GPGGA_MSG_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gl8_msgs::GPGGA_MSG_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "hdop: ";
    Printer<double>::stream(s, indent + "  ", v.hdop);
    s << indent << "num_satellites: ";
    Printer<double>::stream(s, indent + "  ", v.num_satellites);
    s << indent << "fix_type: ";
    Printer<double>::stream(s, indent + "  ", v.fix_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GL8_MSGS_MESSAGE_GPGGA_MSG_H
