// Generated by gencpp from file gl8_msgs/MapNearby.msg
// DO NOT EDIT!


#ifndef GL8_MSGS_MESSAGE_MAPNEARBY_H
#define GL8_MSGS_MESSAGE_MAPNEARBY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/MultiArrayLayout.h>
#include <gl8_msgs/RoadSegment.h>

namespace gl8_msgs
{
template <class ContainerAllocator>
struct MapNearby_
{
  typedef MapNearby_<ContainerAllocator> Type;

  MapNearby_()
    : header()
    , status(false)
    , layout()
    , road()  {
    }
  MapNearby_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(false)
    , layout(_alloc)
    , road(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _status_type;
  _status_type status;

   typedef  ::std_msgs::MultiArrayLayout_<ContainerAllocator>  _layout_type;
  _layout_type layout;

   typedef std::vector< ::gl8_msgs::RoadSegment_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::gl8_msgs::RoadSegment_<ContainerAllocator> >::other >  _road_type;
  _road_type road;




  typedef boost::shared_ptr< ::gl8_msgs::MapNearby_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gl8_msgs::MapNearby_<ContainerAllocator> const> ConstPtr;

}; // struct MapNearby_

typedef ::gl8_msgs::MapNearby_<std::allocator<void> > MapNearby;

typedef boost::shared_ptr< ::gl8_msgs::MapNearby > MapNearbyPtr;
typedef boost::shared_ptr< ::gl8_msgs::MapNearby const> MapNearbyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gl8_msgs::MapNearby_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gl8_msgs::MapNearby_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gl8_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'gl8_msgs': ['/home/hl/google/src/gl8_msgs /msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::MapNearby_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::MapNearby_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::MapNearby_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::MapNearby_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::MapNearby_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::MapNearby_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gl8_msgs::MapNearby_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bdfa622e60bd6bfe837b9b8ca5046e7";
  }

  static const char* value(const ::gl8_msgs::MapNearby_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bdfa622e60bd6bfULL;
  static const uint64_t static_value2 = 0xe837b9b8ca5046e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::gl8_msgs::MapNearby_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gl8_msgs/MapNearby";
  }

  static const char* value(const ::gl8_msgs::MapNearby_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gl8_msgs::MapNearby_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
bool status\n\
std_msgs/MultiArrayLayout layout\n\
RoadSegment[] road\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding elements at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
================================================================================\n\
MSG: gl8_msgs/RoadSegment\n\
bool type \n\
# if the road segment is line, the value of type is 0;\n\
# if the road segment is curve, the value of type is 1; \n\
float64 length\n\
Point2D origin\n\
Point2D terminus\n\
# below parameters are for curve segments\n\
# if the road turns counterclockwise, then turn_direction is 0\n\
# if the road turns clockwise, then turn_direction is 1\n\
bool turn_direction\n\
Point2D center\n\
float64 radius\n\
Vector2 start_direction\n\
Vector2 end_direction\n\
\n\
\n\
\n\
\n\
================================================================================\n\
MSG: gl8_msgs/Point2D\n\
float64 x\n\
float64 y\n\
\n\
================================================================================\n\
MSG: gl8_msgs/Vector2\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::gl8_msgs::MapNearby_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gl8_msgs::MapNearby_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.layout);
      stream.next(m.road);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapNearby_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gl8_msgs::MapNearby_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gl8_msgs::MapNearby_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "layout: ";
    s << std::endl;
    Printer< ::std_msgs::MultiArrayLayout_<ContainerAllocator> >::stream(s, indent + "  ", v.layout);
    s << indent << "road[]" << std::endl;
    for (size_t i = 0; i < v.road.size(); ++i)
    {
      s << indent << "  road[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gl8_msgs::RoadSegment_<ContainerAllocator> >::stream(s, indent + "    ", v.road[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GL8_MSGS_MESSAGE_MAPNEARBY_H
