// Generated by gencpp from file gl8_msgs/PathPoint.msg
// DO NOT EDIT!


#ifndef GL8_MSGS_MESSAGE_PATHPOINT_H
#define GL8_MSGS_MESSAGE_PATHPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gl8_msgs
{
template <class ContainerAllocator>
struct PathPoint_
{
  typedef PathPoint_<ContainerAllocator> Type;

  PathPoint_()
    : id(0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)
    , kappa(0.0)  {
    }
  PathPoint_(const ContainerAllocator& _alloc)
    : id(0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)
    , kappa(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;

   typedef double _kappa_type;
  _kappa_type kappa;




  typedef boost::shared_ptr< ::gl8_msgs::PathPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gl8_msgs::PathPoint_<ContainerAllocator> const> ConstPtr;

}; // struct PathPoint_

typedef ::gl8_msgs::PathPoint_<std::allocator<void> > PathPoint;

typedef boost::shared_ptr< ::gl8_msgs::PathPoint > PathPointPtr;
typedef boost::shared_ptr< ::gl8_msgs::PathPoint const> PathPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gl8_msgs::PathPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gl8_msgs::PathPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gl8_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'gl8_msgs': ['/home/hl/google/src/gl8_msgs /msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::PathPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::PathPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::PathPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::PathPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::PathPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::PathPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gl8_msgs::PathPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5856dd234a5a05d868d75585d8a5c21";
  }

  static const char* value(const ::gl8_msgs::PathPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5856dd234a5a05dULL;
  static const uint64_t static_value2 = 0x868d75585d8a5c21ULL;
};

template<class ContainerAllocator>
struct DataType< ::gl8_msgs::PathPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gl8_msgs/PathPoint";
  }

  static const char* value(const ::gl8_msgs::PathPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gl8_msgs::PathPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n\
float64 x \n\
float64 y \n\
float64 theta\n\
float64 kappa\n\
";
  }

  static const char* value(const ::gl8_msgs::PathPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gl8_msgs::PathPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.kappa);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gl8_msgs::PathPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gl8_msgs::PathPoint_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "kappa: ";
    Printer<double>::stream(s, indent + "  ", v.kappa);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GL8_MSGS_MESSAGE_PATHPOINT_H
