// Generated by gencpp from file gl8_msgs/VehicleControlCmd.msg
// DO NOT EDIT!


#ifndef GL8_MSGS_MESSAGE_VEHICLECONTROLCMD_H
#define GL8_MSGS_MESSAGE_VEHICLECONTROLCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gl8_msgs
{
template <class ContainerAllocator>
struct VehicleControlCmd_
{
  typedef VehicleControlCmd_<ContainerAllocator> Type;

  VehicleControlCmd_()
    : header()
    , is_updated(false)
    , steer_cmd(0.0)
    , speed_cmd(0.0)
    , acc_cmd(0.0)
    , dec_cmd(0.0)  {
    }
  VehicleControlCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_updated(false)
    , steer_cmd(0.0)
    , speed_cmd(0.0)
    , acc_cmd(0.0)
    , dec_cmd(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_updated_type;
  _is_updated_type is_updated;

   typedef double _steer_cmd_type;
  _steer_cmd_type steer_cmd;

   typedef double _speed_cmd_type;
  _speed_cmd_type speed_cmd;

   typedef double _acc_cmd_type;
  _acc_cmd_type acc_cmd;

   typedef double _dec_cmd_type;
  _dec_cmd_type dec_cmd;




  typedef boost::shared_ptr< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleControlCmd_

typedef ::gl8_msgs::VehicleControlCmd_<std::allocator<void> > VehicleControlCmd;

typedef boost::shared_ptr< ::gl8_msgs::VehicleControlCmd > VehicleControlCmdPtr;
typedef boost::shared_ptr< ::gl8_msgs::VehicleControlCmd const> VehicleControlCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gl8_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'gl8_msgs': ['/home/hl/google/src/gl8_msgs /msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da750596c728e0dd356ac699beb73c77";
  }

  static const char* value(const ::gl8_msgs::VehicleControlCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda750596c728e0ddULL;
  static const uint64_t static_value2 = 0x356ac699beb73c77ULL;
};

template<class ContainerAllocator>
struct DataType< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gl8_msgs/VehicleControlCmd";
  }

  static const char* value(const ::gl8_msgs::VehicleControlCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool is_updated\n\
float64 steer_cmd  #target steer angle\n\
float64 speed_cmd  #target speed \n\
float64 acc_cmd    #target acceleration\n\
float64 dec_cmd    #target deceleration\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gl8_msgs::VehicleControlCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_updated);
      stream.next(m.steer_cmd);
      stream.next(m.speed_cmd);
      stream.next(m.acc_cmd);
      stream.next(m.dec_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleControlCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gl8_msgs::VehicleControlCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gl8_msgs::VehicleControlCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_updated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_updated);
    s << indent << "steer_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.steer_cmd);
    s << indent << "speed_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.speed_cmd);
    s << indent << "acc_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.acc_cmd);
    s << indent << "dec_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.dec_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GL8_MSGS_MESSAGE_VEHICLECONTROLCMD_H
