// Generated by gencpp from file gl8_msgs/VehicleSpeedFeedBack.msg
// DO NOT EDIT!


#ifndef GL8_MSGS_MESSAGE_VEHICLESPEEDFEEDBACK_H
#define GL8_MSGS_MESSAGE_VEHICLESPEEDFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gl8_msgs
{
template <class ContainerAllocator>
struct VehicleSpeedFeedBack_
{
  typedef VehicleSpeedFeedBack_<ContainerAllocator> Type;

  VehicleSpeedFeedBack_()
    : header()
    , is_updated(false)
    , front_wheel_speed(0.0)
    , rear_wheel_speed(0.0)
    , front_left_pulse(0.0)
    , front_right_pulse(0.0)
    , rear_left_pulse(0.0)
    , rear_right_pulse(0.0)  {
    }
  VehicleSpeedFeedBack_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_updated(false)
    , front_wheel_speed(0.0)
    , rear_wheel_speed(0.0)
    , front_left_pulse(0.0)
    , front_right_pulse(0.0)
    , rear_left_pulse(0.0)
    , rear_right_pulse(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_updated_type;
  _is_updated_type is_updated;

   typedef double _front_wheel_speed_type;
  _front_wheel_speed_type front_wheel_speed;

   typedef double _rear_wheel_speed_type;
  _rear_wheel_speed_type rear_wheel_speed;

   typedef double _front_left_pulse_type;
  _front_left_pulse_type front_left_pulse;

   typedef double _front_right_pulse_type;
  _front_right_pulse_type front_right_pulse;

   typedef double _rear_left_pulse_type;
  _rear_left_pulse_type rear_left_pulse;

   typedef double _rear_right_pulse_type;
  _rear_right_pulse_type rear_right_pulse;




  typedef boost::shared_ptr< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleSpeedFeedBack_

typedef ::gl8_msgs::VehicleSpeedFeedBack_<std::allocator<void> > VehicleSpeedFeedBack;

typedef boost::shared_ptr< ::gl8_msgs::VehicleSpeedFeedBack > VehicleSpeedFeedBackPtr;
typedef boost::shared_ptr< ::gl8_msgs::VehicleSpeedFeedBack const> VehicleSpeedFeedBackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gl8_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'gl8_msgs': ['/home/hl/google/src/gl8_msgs /msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86b4891460c1e2b11ebe5987399947a1";
  }

  static const char* value(const ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86b4891460c1e2b1ULL;
  static const uint64_t static_value2 = 0x1ebe5987399947a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gl8_msgs/VehicleSpeedFeedBack";
  }

  static const char* value(const ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool is_updated\n\
float64 front_wheel_speed   # m/s\n\
float64 rear_wheel_speed    # m/s\n\
float64 front_left_pulse\n\
float64 front_right_pulse\n\
float64 rear_left_pulse\n\
float64 rear_right_pulse\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_updated);
      stream.next(m.front_wheel_speed);
      stream.next(m.rear_wheel_speed);
      stream.next(m.front_left_pulse);
      stream.next(m.front_right_pulse);
      stream.next(m.rear_left_pulse);
      stream.next(m.rear_right_pulse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleSpeedFeedBack_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gl8_msgs::VehicleSpeedFeedBack_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_updated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_updated);
    s << indent << "front_wheel_speed: ";
    Printer<double>::stream(s, indent + "  ", v.front_wheel_speed);
    s << indent << "rear_wheel_speed: ";
    Printer<double>::stream(s, indent + "  ", v.rear_wheel_speed);
    s << indent << "front_left_pulse: ";
    Printer<double>::stream(s, indent + "  ", v.front_left_pulse);
    s << indent << "front_right_pulse: ";
    Printer<double>::stream(s, indent + "  ", v.front_right_pulse);
    s << indent << "rear_left_pulse: ";
    Printer<double>::stream(s, indent + "  ", v.rear_left_pulse);
    s << indent << "rear_right_pulse: ";
    Printer<double>::stream(s, indent + "  ", v.rear_right_pulse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GL8_MSGS_MESSAGE_VEHICLESPEEDFEEDBACK_H
