// Generated by gencpp from file gl8_msgs/VehicleSteerFeedBack.msg
// DO NOT EDIT!


#ifndef GL8_MSGS_MESSAGE_VEHICLESTEERFEEDBACK_H
#define GL8_MSGS_MESSAGE_VEHICLESTEERFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gl8_msgs
{
template <class ContainerAllocator>
struct VehicleSteerFeedBack_
{
  typedef VehicleSteerFeedBack_<ContainerAllocator> Type;

  VehicleSteerFeedBack_()
    : header()
    , is_updated(false)
    , steer_angle(0.0)
    , steer_rate(0.0)  {
    }
  VehicleSteerFeedBack_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_updated(false)
    , steer_angle(0.0)
    , steer_rate(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_updated_type;
  _is_updated_type is_updated;

   typedef double _steer_angle_type;
  _steer_angle_type steer_angle;

   typedef double _steer_rate_type;
  _steer_rate_type steer_rate;




  typedef boost::shared_ptr< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleSteerFeedBack_

typedef ::gl8_msgs::VehicleSteerFeedBack_<std::allocator<void> > VehicleSteerFeedBack;

typedef boost::shared_ptr< ::gl8_msgs::VehicleSteerFeedBack > VehicleSteerFeedBackPtr;
typedef boost::shared_ptr< ::gl8_msgs::VehicleSteerFeedBack const> VehicleSteerFeedBackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gl8_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'gl8_msgs': ['/home/hl/google/src/gl8_msgs /msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc16d3ad0204b91c33e3dc819e06b316";
  }

  static const char* value(const ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc16d3ad0204b91cULL;
  static const uint64_t static_value2 = 0x33e3dc819e06b316ULL;
};

template<class ContainerAllocator>
struct DataType< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gl8_msgs/VehicleSteerFeedBack";
  }

  static const char* value(const ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool is_updated\n\
float64 steer_angle # degree\n\
float64 steer_rate  # rad/s\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_updated);
      stream.next(m.steer_angle);
      stream.next(m.steer_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleSteerFeedBack_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gl8_msgs::VehicleSteerFeedBack_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_updated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_updated);
    s << indent << "steer_angle: ";
    Printer<double>::stream(s, indent + "  ", v.steer_angle);
    s << indent << "steer_rate: ";
    Printer<double>::stream(s, indent + "  ", v.steer_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GL8_MSGS_MESSAGE_VEHICLESTEERFEEDBACK_H
