(cl:in-package can_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIMEOFISSUE-VAL
          TIMEOFISSUE
          MAGNETDATA-VAL
          MAGNETDATA
          MAGOFFSETFROMMIDDLE-VAL
          MAGOFFSETFROMMIDDLE
          FIT_VARIANCE-VAL
          FIT_VARIANCE
          GAUSS_K-VAL
          GAUSS_K
          RMS_ERROR-VAL
          RMS_ERROR
          MILEAGE-VAL
          MILEAGE
          FRAME_VARIANCE-VAL
          FRAME_VARIANCE
          MAGNETCOUNTERDEBUG-VAL
          MAGNETCOUNTERDEBUG
          MAGNETCOUNTERTRIGGER-VAL
          MAGNETCOUNTERTRIGGER
          POLARITYCODE-VAL
          POLARITYCODE
          MAGNETPOLARITY-VAL
          MAGNETPOLARITY
))