# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from can_msgs/MagFitInfoArray.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import std_msgs.msg

class MagFitInfoArray(genpy.Message):
  _md5sum = "ceab1ab410175fbe7c0e5f393ad64bd9"
  _type = "can_msgs/MagFitInfoArray"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
time TimeOfIssue

int32 MagnetPolarity
float32 frame_variance
uint32 PolarityCode
float32 MagOffsetFromMiddle
float32 fit_variance
float32 RMS_error
float32 Mileage




================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','TimeOfIssue','MagnetPolarity','frame_variance','PolarityCode','MagOffsetFromMiddle','fit_variance','RMS_error','Mileage']
  _slot_types = ['std_msgs/Header','time','int32','float32','uint32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,TimeOfIssue,MagnetPolarity,frame_variance,PolarityCode,MagOffsetFromMiddle,fit_variance,RMS_error,Mileage

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MagFitInfoArray, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.TimeOfIssue is None:
        self.TimeOfIssue = genpy.Time()
      if self.MagnetPolarity is None:
        self.MagnetPolarity = 0
      if self.frame_variance is None:
        self.frame_variance = 0.
      if self.PolarityCode is None:
        self.PolarityCode = 0
      if self.MagOffsetFromMiddle is None:
        self.MagOffsetFromMiddle = 0.
      if self.fit_variance is None:
        self.fit_variance = 0.
      if self.RMS_error is None:
        self.RMS_error = 0.
      if self.Mileage is None:
        self.Mileage = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.TimeOfIssue = genpy.Time()
      self.MagnetPolarity = 0
      self.frame_variance = 0.
      self.PolarityCode = 0
      self.MagOffsetFromMiddle = 0.
      self.fit_variance = 0.
      self.RMS_error = 0.
      self.Mileage = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2IifI4f.pack(_x.TimeOfIssue.secs, _x.TimeOfIssue.nsecs, _x.MagnetPolarity, _x.frame_variance, _x.PolarityCode, _x.MagOffsetFromMiddle, _x.fit_variance, _x.RMS_error, _x.Mileage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.TimeOfIssue is None:
        self.TimeOfIssue = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.TimeOfIssue.secs, _x.TimeOfIssue.nsecs, _x.MagnetPolarity, _x.frame_variance, _x.PolarityCode, _x.MagOffsetFromMiddle, _x.fit_variance, _x.RMS_error, _x.Mileage,) = _struct_2IifI4f.unpack(str[start:end])
      self.TimeOfIssue.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2IifI4f.pack(_x.TimeOfIssue.secs, _x.TimeOfIssue.nsecs, _x.MagnetPolarity, _x.frame_variance, _x.PolarityCode, _x.MagOffsetFromMiddle, _x.fit_variance, _x.RMS_error, _x.Mileage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.TimeOfIssue is None:
        self.TimeOfIssue = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.TimeOfIssue.secs, _x.TimeOfIssue.nsecs, _x.MagnetPolarity, _x.frame_variance, _x.PolarityCode, _x.MagOffsetFromMiddle, _x.fit_variance, _x.RMS_error, _x.Mileage,) = _struct_2IifI4f.unpack(str[start:end])
      self.TimeOfIssue.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_2IifI4f = struct.Struct("<2IifI4f")
