# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from can_msgs/MagDataAndFitResult.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import std_msgs.msg

class MagDataAndFitResult(genpy.Message):
  _md5sum = "d316795fd42d0d5785fda2dad9fbdd20"
  _type = "can_msgs/MagDataAndFitResult"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
time TimeOfIssue

float32[] MagnetData
float32 MagOffsetFromMiddle
float32 fit_variance
float32 gauss_k
float32 RMS_error
float32 Mileage
float32 frame_variance
uint32  MagnetCounterDebug
int8 MagnetCounterTrigger
uint32 PolarityCode
int32   MagnetPolarity

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','TimeOfIssue','MagnetData','MagOffsetFromMiddle','fit_variance','gauss_k','RMS_error','Mileage','frame_variance','MagnetCounterDebug','MagnetCounterTrigger','PolarityCode','MagnetPolarity']
  _slot_types = ['std_msgs/Header','time','float32[]','float32','float32','float32','float32','float32','float32','uint32','int8','uint32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,TimeOfIssue,MagnetData,MagOffsetFromMiddle,fit_variance,gauss_k,RMS_error,Mileage,frame_variance,MagnetCounterDebug,MagnetCounterTrigger,PolarityCode,MagnetPolarity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MagDataAndFitResult, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.TimeOfIssue is None:
        self.TimeOfIssue = genpy.Time()
      if self.MagnetData is None:
        self.MagnetData = []
      if self.MagOffsetFromMiddle is None:
        self.MagOffsetFromMiddle = 0.
      if self.fit_variance is None:
        self.fit_variance = 0.
      if self.gauss_k is None:
        self.gauss_k = 0.
      if self.RMS_error is None:
        self.RMS_error = 0.
      if self.Mileage is None:
        self.Mileage = 0.
      if self.frame_variance is None:
        self.frame_variance = 0.
      if self.MagnetCounterDebug is None:
        self.MagnetCounterDebug = 0
      if self.MagnetCounterTrigger is None:
        self.MagnetCounterTrigger = 0
      if self.PolarityCode is None:
        self.PolarityCode = 0
      if self.MagnetPolarity is None:
        self.MagnetPolarity = 0
    else:
      self.header = std_msgs.msg.Header()
      self.TimeOfIssue = genpy.Time()
      self.MagnetData = []
      self.MagOffsetFromMiddle = 0.
      self.fit_variance = 0.
      self.gauss_k = 0.
      self.RMS_error = 0.
      self.Mileage = 0.
      self.frame_variance = 0.
      self.MagnetCounterDebug = 0
      self.MagnetCounterTrigger = 0
      self.PolarityCode = 0
      self.MagnetPolarity = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.TimeOfIssue.secs, _x.TimeOfIssue.nsecs))
      length = len(self.MagnetData)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.MagnetData))
      _x = self
      buff.write(_struct_6fIbIi.pack(_x.MagOffsetFromMiddle, _x.fit_variance, _x.gauss_k, _x.RMS_error, _x.Mileage, _x.frame_variance, _x.MagnetCounterDebug, _x.MagnetCounterTrigger, _x.PolarityCode, _x.MagnetPolarity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.TimeOfIssue is None:
        self.TimeOfIssue = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.TimeOfIssue.secs, _x.TimeOfIssue.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.MagnetData = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 37
      (_x.MagOffsetFromMiddle, _x.fit_variance, _x.gauss_k, _x.RMS_error, _x.Mileage, _x.frame_variance, _x.MagnetCounterDebug, _x.MagnetCounterTrigger, _x.PolarityCode, _x.MagnetPolarity,) = _struct_6fIbIi.unpack(str[start:end])
      self.TimeOfIssue.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.TimeOfIssue.secs, _x.TimeOfIssue.nsecs))
      length = len(self.MagnetData)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.MagnetData.tostring())
      _x = self
      buff.write(_struct_6fIbIi.pack(_x.MagOffsetFromMiddle, _x.fit_variance, _x.gauss_k, _x.RMS_error, _x.Mileage, _x.frame_variance, _x.MagnetCounterDebug, _x.MagnetCounterTrigger, _x.PolarityCode, _x.MagnetPolarity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.TimeOfIssue is None:
        self.TimeOfIssue = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.TimeOfIssue.secs, _x.TimeOfIssue.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.MagnetData = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 37
      (_x.MagOffsetFromMiddle, _x.fit_variance, _x.gauss_k, _x.RMS_error, _x.Mileage, _x.frame_variance, _x.MagnetCounterDebug, _x.MagnetCounterTrigger, _x.PolarityCode, _x.MagnetPolarity,) = _struct_6fIbIi.unpack(str[start:end])
      self.TimeOfIssue.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_2I = struct.Struct("<2I")
_struct_6fIbIi = struct.Struct("<6fIbIi")
